version: "3.7"

services:
  mixpro:
    build: ./
    container_name: mixpro
    restart: always
    ports:
      - "3726:3000"
    command: "npm run dev"
    networks:
      - nuxt-network
    volumes:
      - '.:/var/www/mixpro'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  nuxt-network:
    driver: bridge
